---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |-
        prometheus-node-exporter:
           hostRootFsMount:
             enabled: false
        prometheusOperator:
           admissionWebhooks:
             failurePolicy: Ignore

        alertmanager:
          service:
            type: ClusterIP
            ports:
              http: 80
              https: 443
          ingress:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "grafana-letsencrypt-prod"
            hosts:
              - alertmanager.malko2.of.by
            tls:
              - secretName: grafana-tls
                hosts:
                  - alertmanager.malko2.of.by
        prometheus:
          service:
            type: ClusterIP
            ports:
              http: 80
              https: 443
          ingress:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "grafana-letsencrypt-prod"
            hosts:
              - prometheus.malko2.of.by
            tls:
              - secretName: grafana-tls
                hosts:
                  - prometheus.malko2.of.by


        grafana:
          service:
            type: ClusterIP
            ports:
              http: 80
              https: 443
          ingress:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "grafana-letsencrypt-prod"
            hosts:
              - grafana.malko2.of.by
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.malko2.of.by

          grafana.ini:
            server:
              root_url: https://grafana.malko2.of.by
            auth.generic_oauth:
              enabled: true
              name: Keycloak
              allow_sign_up: true
              scopes: profile,email,groups
              client_id: grafana
              client_secret: grafana-client-secret
              auth_url: http://35.193.212.134:8080/auth/realms/master/protocol/openid-connect/auth
              token_url: http://35.193.212.134:8080/auth/realms/master/protocol/openid-connect/token
              api_url: http://35.193.212.134:8080/auth/realms/master/protocol/openid-connect/userinfo
              role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-dev') && 'Editor' || 'Viewer'

    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 42.0.3
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
