---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: chatcord
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/salamirangerover/chatcord-chart.git
    targetRevision: HEAD
    path: chart
  destination:
    namespace: chatcord
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
