---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: "1.12.1"
    helm:
      values: |
        provider: google
        sources: [service, ingress]
        domainFilters: [malko2.of.by]
        logFormat: json
        policy: upsert-only
        registry: txt
        txtOwnerId: "gmalko"

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
