---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: grafana/loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 4.8.0
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
