apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 6.14.4
    helm:
      values: |
        sources:
          - --source=service
          - --source=ingress
          - --domain-filter=malko2.of.by # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
          - --provider=google
          - --log-format=json # google cloud logs parses severity of the "text" log format incorrectly
          #- --google-project=my-cloud-dns-project # Use this to specify a project different from the one external-dns is running inside
          - --google-zone-visibility=public # Use this to filter to only zones with this visibility. Set to either 'public' or 'private'. Omitting will match public and private zones
          - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
          - --registry=txt
          - --txt-owner-id=my-identifier

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
