---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/salamirangerover/gcp-gitops-project.git
      targetRevision: master
      ref: helmValues

    - repoURL: https://charts.bitnami.com/bitnami
      chart: external-dns
      targetRevision: 6.14.4
      helm:
        valueFiles:
          - $helmValues/manifests/_init/applications/external-dns/external-dns-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
