apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 6.14.4
    helm:
      values: |
        sources:
          - service
          - ingress
          - --domain-filter=malko2.of.by 
          - --provider=google
          - --log-format=json 
          - --google-project=salamirangerover
          - --google-zone-visibility=public
          - --policy=upsert-only
          - --registry=txt
          - --txt-owner-id=gmalko

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
