---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sealed-secret
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/secrets
    repoURL: https://github.com/salamirangerover/gcp-gitops-project.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
