apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls-certificate
  namespace: argocd
spec:
  secretName: argocd-tls-secret
  issuerRef:
    name: argocd-tls-issuer
    kind: Issuer
  dnsNames:
  - argocd.malko2.of.by
