# issuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: argocd-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: glebmalko@gmail.com # ❗ Replace this with your email address
    privateKeySecretRef:
      name: argocd-letsencrypt-prod
    solvers:
    - http01:
        ingress:
          name: argocdserver-ingress
