---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: wordpress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: "15.2.2"
    helm:
      values: |
        wordpressUsername: admin
        wordpressPassword: 123qweASD
        wordpressFirstName: Malko
        wordpressLastName: App
        wordpressBlogName: Blog
        wordpressEmail: gleb.malko@hoster.by

        service:
          type: ClusterIP
          ports:
            http: 80
            https: 443

        ingress:
          enabled: true
          certManager: true
          pathType: ImplementationSpecific
          apiVersion: ""
          ingressClassName: "nginx"
          hostname: wordpress.malko2.of.by
          path: /
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
          

          tls: true
          extraTls:
            - hosts:
                - wordpress.malko2.of.by
                  
                secretName: wordpress.tls
          
          selfSigned: false


        mariadb:
          enabled: true
          architecture: standalone
          auth:
            rootPassword: "mariadb"
            database: bitnami_wordpress
            username: bn_wordpress
            password: "mariadb"
         
        memcached:
          enabled: true
          auth:
            enabled: true
            username: "admin"
            password: "qwerty"
  destination:
    namespace: default
    server: https://kubernetes.default.svc    

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
