apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tls-sealed-secret
spec:
  destination:
    namespace: <ваше_пространство_имен>
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/secrets
    repoURL: https://github.com/salamirangerover/gcp-gitops-project.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  syncWave: 1
