---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/salamirangerover/gcp-gitops-project.git
      targetRevision: master
      ref: helmValues
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: "2.7.*"
      helm:
        valueFiles:
            - $helmValues/manifests/helm-values/sealed-secrets-values.yml

  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  info:
    - name: REF, app
      value: https://github.com/bitnami-labs/sealed-secrets
    - name: REF, chart
      value: https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets
    - name: REF, docs
      value: TODO - add documentation
