---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sealedsecrets-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: "2.7.*"
      helm:
        values: |
          nameOverride: ""
          fullnameOverride: ""
          namespace: ""

          image:
            registry: docker.io
            repository: bitnami/sealed-secrets-controller
            tag: v0.19.5
            pullPolicy: IfNotPresent

          createController: true

  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  info:
    - name: REF, app
      value: https://github.com/bitnami-labs/sealed-secrets
    - name: REF, chart
      value: https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets
    - name: REF, docs
      value: TODO - add documentation
