---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |-
        prometheus-node-exporter:
           hostRootFsMount:
             enabled: false
        prometheusOperator:
           admissionWebhooks:
             failurePolicy: Ignore

        prometheus:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts: ['prometheus.malko2.of.by']
          paths: ['/']
          tls:
          - secretName: prometheus-tls
          hosts:
          - prometheus.k3s.local
          
          prometheusSpec:
            externalUrl: "https://prometheus.malko2.of.by/"
            routePrefix: /

        grafana:
#          service:
#            type: LoadBalancer
#            ports:
#              http: 80
#              https: 443
            

          ingress:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-production"
            hosts:
              - grafana.malko2.of.by
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.malko2.of.by
          grafana.ini:
            server:
              root_url: https://grafana.malko2.of.by

    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 42.0.3
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true

