---
# REVIEW:
# Документация по GAP стеку:
# https://purple-lettuce-23a.notion.site/Prometheus-Certified-Associate-PCA-f74d585003c24e13887f7ebca76001b6
# https://karma-git.github.io/Andrew-Horbach.github.io-Public/docs/observability/1-otus-observability
# 1. Сделать алертинг в какой-нибудь канал, лучше в 2 с разделением алертов
# 2. Добавить обзор wordpress-а и всех других инфраструктурных компонентов
# 3. Сделать свое приложение и его тоже мониторить
# 4. Сделать дашборды в графане по этому делу
# 5. Реализовать систему сбора и хранения логов, предлагаю grafana loki

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |-
        prometheus-node-exporter:
           hostRootFsMount:
             enabled: false
        prometheusOperator:
           admissionWebhooks:
             failurePolicy: Ignore

        alertmanager:
          service:
            type: ClusterIP
            ports:
              http: 80
              https: 443
           
          ingress:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "prometheus-letsencrypt-prod"
            hosts:
              - alertmanager.malko2.of.by
            tls:
              - secretName: grafana-tls
                hosts:
                  - alertmanager.malko2.of.by



        prometheus:
          service:
            type: ClusterIP
            ports:
              http: 80
              https: 443
           
          ingress:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "prometheus-letsencrypt-prod"
            hosts:
              - prometheus.malko2.of.by
            tls:
              - secretName: grafana-tls
                hosts:
                  - prometheus.malko2.of.by


        grafana:
          service:
            type: ClusterIP
            ports:
              http: 80
              https: 443
            

          ingress:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "grafana-letsencrypt-prod"
            hosts:
              - grafana.malko2.of.by
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.malko2.of.by

          grafana.ini:
            server:
              root_url: https://grafana.malko2.of.by

    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.7.1
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true

