---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/salamirangerover/gcp-gitops-project
      path: manifests/applications/cert-manager/cluster-issuers
      targetRevision: HEAD
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.8.2
      helm:
        values: |-
          installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
