---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: wordpress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/salamirangerover/gcp-gitops-project.git
      targetRevision: master
      ref: helmValues
    - repoURL: https://charts.bitnami.com/bitnami
      chart: wordpress
      targetRevision: "15.2.2"
      helm:
        valueFiles:
          - $helmValues/manifests/applications/wordpress/wp-values.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
