---


nameOverride: ""
fullnameOverride: ""


namespace: ""


image:
  registry: docker.io
  repository: bitnami/sealed-secrets-controller
  tag: v0.19.5
  pullPolicy: IfNotPresent


createController: true


## @param secretName The name of an existing TLS secret containing the key used to encrypt secrets
##
secretName: "sealed-secrets-key"
## @param updateStatus Specifies whether the Sealed Secrets controller should update the status subresource
##
updateStatus: true
## @param skipRecreate Specifies whether the Sealed Secrets controller should skip recreating removed secrets
## Setting it to false allows to optionally restore backward compatibility in low priviledge
## environments when old versions of the controller did not require watch permissions on secrets
## for secret re-creation.
##
skipRecreate: false
## @param keyrenewperiod Specifies key renewal period. Default 30 days
## e.g
## keyrenewperiod: "720h30m"
##
keyrenewperiod: ""
## @param rateLimit Number of allowed sustained request per second for verify endpoint
##




resources:
  limits: {}
  requests: {}


metrics:
  serviceMonitor:
    enabled: false
  dashboards:
    create: false
