---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: user-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/salamirangerover/gcp-gitops-project.git
    targetRevision: master
    path: manifests/user_applications
    directory:
      recurse: true
  destination:
    namespace: init-app
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
