---
name: infra
on:
  push:
    branches:
      - "master"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Terraform lint
        run: "terraform fmt -check=true -diff=true -recursive \ntflint --chdir=terraform\n"
      - name: YAML lint
        run: yamllint manifests/
