name: nodejs-ci

on:
  push:
    branches:
      - "master"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: nodejs-app/
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: nodejs-app/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./nodejs-app
          push: true
          tags: salamirangerover/node-web-app:1.2
