name: nodejs-ci

on:
  push:
    branches:
      - "master"

jobs:
  nodejs_app_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          target: nodejs-app/
      - run: cd nodejs-app/ && npm ci
      - run: npm run build --if-present
      - run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y terraform-lint yamllint

      - name: Terraform lint
        run: |
          terraform fmt -check=true -diff=true
          tflint --chdir=terraform

      - name: YAML lint
        run: yamllint manifests/

  build_image:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./nodejs-app
          push: true
          tags: salamirangerover/node-web-app:1.2
